#!/usr/bin/env node
/**
 * create-tally-holder — interactive scaffold.
 *
 * Flow:
 *   1. Resolve target directory (from argv or prompt)
 *   2. Prompt for relay URL, node name, data dir, listen port, public URL (optional)
 *   3. Copy template/ into target dir
 *   4. Generate Ed25519 keypair, write data/identity.json (0600)
 *   5. Write .env with config + derived agent_id
 *   6. Print next-steps instructions
 */

import { createInterface, Interface as ReadlineInterface } from "node:readline";
import { fileURLToPath } from "node:url";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = path.resolve(__dirname, "..", "template");

const DEFAULT_RELAY = "https://api.tally.qisprotocol.com";
const DEFAULT_PORT = "7894";

const argv = process.argv.slice(2);
const NON_INTERACTIVE = argv.includes("--yes") || argv.includes("-y");
const positional = argv.filter((a) => !a.startsWith("-"));

type Answers = {
  targetDir: string;
  nodeName: string;
  relayUrl: string;
  dataDir: string;
  listenPort: string;
  publicUrl: string;
};

/* ── Prompt helpers ─────────────────────────────────────────── */

let rl: ReadlineInterface | null = null;

function ask(question: string, fallback: string = ""): Promise<string> {
  if (NON_INTERACTIVE) return Promise.resolve(fallback);
  if (!rl) rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    const suffix = fallback ? ` (${fallback})` : "";
    rl!.question(`${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || fallback);
    });
  });
}

function closeRl() {
  if (rl) rl.close();
  rl = null;
}

/* ── Scaffold ops ───────────────────────────────────────────── */

function copyDir(src: string, dst: string) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const dstPath = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      copyDir(srcPath, dstPath);
    } else {
      fs.copyFileSync(srcPath, dstPath);
    }
  }
}

function generateIdentity(): { publicKeyHex: string; privateKeyPem: string; agentId: string } {
  const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519");
  const publicKeyHex = publicKey.export({ format: "der", type: "spki" }).toString("hex");
  const privateKeyPem = privateKey.export({ format: "pem", type: "pkcs8" }) as string;
  const agentId = crypto.createHash("sha256").update(publicKeyHex).digest("hex").slice(0, 16);
  return { publicKeyHex, privateKeyPem, agentId };
}

function writeEnv(targetDir: string, answers: Answers, agentId: string) {
  const lines = [
    `# Tally holder config — generated by create-tally-holder`,
    `TALLY_RELAY_URL=${answers.relayUrl}`,
    `TALLY_NODE_NAME=${answers.nodeName}`,
    `TALLY_NODE_ID=${answers.nodeName}-${agentId.slice(0, 6)}`,
    `TALLY_AGENT_ID=${agentId}`,
    `TALLY_DATA_DIR=${answers.dataDir}`,
    `TALLY_LISTEN_PORT=${answers.listenPort}`,
    `TALLY_PUBLIC_URL=${answers.publicUrl}`,
    `TALLY_IDENTITY_PATH=${answers.dataDir}/identity.json`,
  ];
  fs.writeFileSync(path.join(targetDir, ".env"), lines.join("\n") + "\n");
}

function writeIdentity(
  targetDir: string,
  dataDir: string,
  identity: { publicKeyHex: string; privateKeyPem: string; agentId: string },
) {
  const dataPath = path.resolve(targetDir, dataDir);
  fs.mkdirSync(dataPath, { recursive: true });
  const file = path.join(dataPath, "identity.json");
  fs.writeFileSync(
    file,
    JSON.stringify(
      {
        agent_id: identity.agentId,
        public_key: identity.publicKeyHex,
        private_key_pem: identity.privateKeyPem,
        created_at: new Date().toISOString(),
      },
      null,
      2,
    ),
  );
  try {
    fs.chmodSync(file, 0o600);
  } catch {
    /* Windows: chmod is a no-op, best effort */
  }
}

/* ── Main ───────────────────────────────────────────────────── */

async function main() {
  console.log("");
  console.log("  create-tally-holder");
  console.log("  ──────────────────────────────────────────");
  console.log("  Spin up a Tally DHT holder on this machine.");
  console.log("");

  const argDir = positional[0];
  const targetDir = argDir || (await ask("Target directory", "tally-holder"));
  const absTarget = path.resolve(process.cwd(), targetDir);

  if (fs.existsSync(absTarget)) {
    const contents = fs.readdirSync(absTarget);
    if (contents.length > 0) {
      console.error(`\n  ${absTarget} exists and is not empty.`);
      console.error("  Pick a different directory or remove that one.");
      closeRl();
      process.exit(1);
    }
  }

  const nodeName = await ask("Node name (for logs + directory listing)", "tally-holder");
  const relayUrl = await ask("Relay URL", DEFAULT_RELAY);
  const dataDir = await ask("Data directory (relative to project)", "./data");
  const listenPort = await ask("Listen port (for optional inbound mode)", DEFAULT_PORT);
  const publicUrl = await ask(
    "Public URL (leave blank for outbound-only)",
    "",
  );

  const answers: Answers = { targetDir: absTarget, nodeName, relayUrl, dataDir, listenPort, publicUrl };

  console.log("");
  console.log("  Scaffolding...");
  copyDir(TEMPLATE_DIR, absTarget);

  console.log("  Generating Ed25519 identity...");
  const identity = generateIdentity();
  writeIdentity(absTarget, dataDir, identity);
  writeEnv(absTarget, answers, identity.agentId);

  closeRl();

  console.log("");
  console.log("  ──────────────────────────────────────────");
  console.log(`  Node ready at: ${absTarget}`);
  console.log(`  Agent ID:      ${identity.agentId}`);
  console.log(`  Mode:          ${publicUrl ? "inbound + outbound" : "outbound-only"}`);
  console.log("  ──────────────────────────────────────────");
  console.log("");
  console.log("  Next:");
  console.log(`    cd ${targetDir}`);
  console.log(`    npm install`);
  console.log(`    npm start`);
  console.log("");
  console.log("  Your node will register with the relay and begin holding its slice of the network.");
  console.log("");
}

main().catch((err) => {
  console.error(err);
  closeRl();
  process.exit(1);
});
